### ISSUE TITLE
PostgreSQL error : FATAL:  sorry, too many clients already

### ISSUE THREAD

**Issue by vladimir-tsapkov** [MacPaw/together-app#2]
Hi!
Have some issues with growing connections and seems they didn't close after some time.
`select count(1) from pg_stat_activity;
 count
-------
    13
(1 row)`

After 1-2 hours:
`select count(1) from pg_stat_activity;
 count
-------
   104
(1 row)`

Settings are:
`select min_val, max_val from pg_settings where name='max_connections';
 min_val | max_val
---------+---------
 1       | 262143
(1 row)`

After 120-150 in pg_stat_activity application doesn't work and there error in app logs:

`PrismaClientInitializationError:
Invalid `prisma.memberRecord.findFirst()` invocation:

  Error querying the database: db error: FATAL: sorry, too many clients already
    at Object.request (/app/node_modules/@prisma/client/runtime/index.js:39824:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async PrismaClient._request (/app/node_modules/@prisma/client/runtime/index.js:40646:18)
    at async MemberProvider.findBySlackId (webpack-internal:///(api)/./services/MemberProvider.ts:63:24)
    at async HandleActions (webpack-internal:///(api)/./pages/api/slack/action.ts:36:24)
    at async Object.apiResolver (/app/node_modules/next/dist/server/api-utils/node.js:182:9)
    at async DevServer.runApi (/app/node_modules/next/dist/server/next-server.js:386:9)
    at async Object.fn (/app/node_modules/next/dist/server/base-server.js:488:37)
    at async Router.execute (/app/node_modules/next/dist/server/router.js:228:32) {
  clientVersion: '3.11.0',
  errorCode: undefined
}`

How i can fix that without data loss in docker container with PostgreSQL?

Thanks!

BTW this app is great! )

**Comment by raycharius** [comment]
Hi @vladimir-tsapkov! Thanks for the issue, and for the kind words! 

If you are running the application locally either through the provided `docker-compose` file or by using `npm run dev`, it could be due to the way NextJS does hot reloading, according to [this GitHub issue](https://github.com/prisma/prisma/issues/1983).

But if that's not the case, you'll probably want to [configure the connection pool](https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/connection-pool) for `PrismaClient` to comply with actual database configuration, if they don't already.

Let me know if that helps!

**Comment by raycharius** [comment]
Hi @eeaxrchii – the answer I provided from above should help out. Cheers!
