### ISSUE TITLE
Issue while calling slack /together command "[ERROR]  web-api:WebClient:1 invalid url [json-pointer:view/blocks/1/accessory/url]"

### ISSUE THREAD

**Issue by necroua** [MacPaw/together-app#4]
```
2022-03-29T12:30:35.338132+00:00 heroku[router]: at=info method=POST path="/api/slack/action" host=talkable-together-app.herokuapp.com request_id=5a72ce94-2ce8-42e3-9cb8-0256941dcc8d fwd="3.89.79.86" dyno=web.1 connect=1ms service=4ms status=200 bytes=108 protocol=https
2022-03-29T12:30:35.433256+00:00 app[web.1]: [ERROR]  web-api:WebClient:1 invalid url [json-pointer:view/blocks/1/accessory/url]
2022-03-29T12:30:35.433810+00:00 app[web.1]: Error: An API error occurred: invalid_arguments
2022-03-29T12:30:35.433812+00:00 app[web.1]: at platformErrorFromResult (/app/node_modules/@slack/web-api/dist/errors.js:51:33)
2022-03-29T12:30:35.433812+00:00 app[web.1]: at WebClient.apiCall (/app/node_modules/@slack/web-api/dist/WebClient.js:167:56)
2022-03-29T12:30:35.433813+00:00 app[web.1]: at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-03-29T12:30:35.433813+00:00 app[web.1]: at async ModalService.openOrUpdateView (/app/.next/server/chunks/479.js:1620:13)
2022-03-29T12:30:35.433814+00:00 app[web.1]: at async ModalService.renderCheckInSelfConfirmation (/app/.next/server/chunks/479.js:1533:9)
2022-03-29T12:30:35.433814+00:00 app[web.1]: at async HandleActions (/app/.next/server/pages/api/slack/action.js:168:17)
2022-03-29T12:30:35.433815+00:00 app[web.1]: at async Object.apiResolver (/app/node_modules/next/dist/server/api-utils/node.js:182:9)
2022-03-29T12:30:35.433815+00:00 app[web.1]: at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:386:9)
2022-03-29T12:30:35.433816+00:00 app[web.1]: at async Object.fn (/app/node_modules/next/dist/server/base-server.js:488:37)
2022-03-29T12:30:35.433816+00:00 app[web.1]: at async Router.execute (/app/node_modules/next/dist/server/router.js:228:32) {
2022-03-29T12:30:35.433816+00:00 app[web.1]: code: 'slack_webapi_platform_error',
2022-03-29T12:30:35.433817+00:00 app[web.1]: data: {
2022-03-29T12:30:35.433817+00:00 app[web.1]: ok: false,
2022-03-29T12:30:35.433818+00:00 app[web.1]: error: 'invalid_arguments',
2022-03-29T12:30:35.433818+00:00 app[web.1]: response_metadata: { messages: [Array], scopes: [Array] }
2022-03-29T12:30:35.433819+00:00 app[web.1]: }
2022-03-29T12:30:35.433819+00:00 app[web.1]: }
```

**Comment by raycharius** [comment]
Hi @necroua, you might want to console log the `url` property of the params for the `renderCheckInSelfConfirmation(params)` method in the `ModalService` class, it looks like there's an issue there. The problem is probably with the `HOST` environment variable
